name: flutter_recorder
description: "A new Flutter project."

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_sound: ^8.1.9
  permission_handler: ^11.1.0
  path: ^1.8.0
  assets_audio_player: ^3.0.3+3
  intl: ^0.17.0
  path_provider: ^2.1.1
  flutter_audio_waveforms: ^1.2.1+8
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Basier Circle
      fonts:
        - asset: fonts/basier_circle_regular.ttf
